### ISSUE TITLE
bson 

### ISSUE THREAD

**Issue by kndnwn49090** [DongOnee/lova-backend#1]
```
  File "server/python/logical/logical.py", line 3, in <module>
    import pymongo
  File "/home/cap/miniconda3/envs/lova36/lib/python3.6/site-packages/pymongo/__init__.py", line 77, in <module>
    from pymongo.collection import ReturnDocument
  File "/home/cap/miniconda3/envs/lova36/lib/python3.6/site-packages/pymongo/collection.py", line 20, in <module>
    from bson.code import Code
  File "/home/cap/miniconda3/envs/lova36/lib/python3.6/site-packages/bson/code.py", line 18, in <module>
    from bson.py3compat import abc, string_type, PY3, text_type
traceback: 'Traceback (most recent call last):
  File "server/python/logical/logical.py", line 3, in <module>
    import pymongo
  File "/home/cap/miniconda3/envs/lova36/lib/python3.6/site-packages/pymongo/__init__.py", line 77, in <module>
    from pymongo.collection import ReturnDocument
  File "/home/cap/miniconda3/envs/lova36/lib/python3.6/site-packages/pymongo/collection.py", line 20, in <module>
    from bson.code import Code
  File "/home/cap/miniconda3/envs/lova36/lib/python3.6/site-packages/bson/code.py", line 18, in <module>
    from bson.py3compat import abc, string_type, PY3, text_type
  ModuleNotFoundError: No module named 'bson.py3compat'
```
conda env install and run logical.py error

**Comment by DongOnee** [comment]
https://github.com/py-bson/bson/issues/82#issuecomment-434176251

**Comment by kndnwn49090** [comment]
ref. https://github.com/py-bson/bson/issues/82#issuecomment-434176251
```
pip uninstall bson
pip uninstall pymongo
conda install -c anaconda pymongo 
```
